fix: handle and pass through exit codes from both install and run

diff --git a/lens-tree b/lens-tree
--- a/lens-tree
+++ b/lens-tree
@@ -5,7 +5,7 @@
   INPUT_TREE="${1?<input> required}"
   DATA_TREE="${HOLOLENS_DATA?data tree required}"
   NPM_RUN_COMMAND="${HOLOLENS_NPM_RUN_COMMAND?hololens.npm-run.command required}"
-  NPM_RUN_INSTALL="${HOLOLENS_NPM_RUN_INSTALL:-npm install --no-progress --quiet --no-audit --loglevel=error}"
+  NPM_RUN_INSTALL="${HOLOLENS_NPM_RUN_INSTALL:-npm install --no-audit}"
   NPM_RUN_ENV="${HOLOLENS_NPM_RUN_ENV:-production}"
   OUTPUT_DIR="${HOLOLENS_NPM_RUN_OUTPUT_DIR:-dist}"
 
@@ -14,26 +14,30 @@
     exit 1;
   fi
 
-  # export git tree to disk
+  # set up environment
   git holo lens export-tree "${DATA_TREE}"
-
-  # execute npm script
   export CI="true"
 
+  # execute npm install
   echo
   echo "Running: ${NPM_RUN_INSTALL}"
   ${NPM_RUN_INSTALL}
+  install_status=$?
 
+  if [ $install_status -ne 0 ]; then
+    echo -e "\n${NPM_RUN_INSTALL} failed with exit status ${install_status}"
+    exit ${install_status}
+  fi
+
+  # execute configured command
   echo
   echo "Running: NODE_ENV=\"${NPM_RUN_ENV}\" ${NPM_RUN_COMMAND}"
   NODE_ENV="${NPM_RUN_ENV}" npm run ${NPM_RUN_COMMAND}
-
   command_status=$?
 
-  # process result
   if [ $command_status -ne 0 ]; then
     echo -e "\n${NPM_RUN_COMMAND} failed with exit status ${command_status}"
-    exit
+    exit ${command_status}
   fi
 
   echo -e "\n${NPM_RUN_COMMAND} completed successfully"
